### ISSUE TITLE
Upgrade zigbee coordinator and router device firmwares 🐝

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#1521]
# Details

## Pre-requisites

- Clone the cc2538-bsl repository

```bash
git clone https://github.com/JelmerT/cc2538-bsl.git
```

## Coordinator

- Download and extract the newer firmware

```bash
curl -L \
  -o CC1352P2_CC2652P_launchpad_coordinator_20210120.zip \
  https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20210120.zip

unzip CC1352P2_CC2652P_launchpad_coordinator_20210120.zip
```

- Scale down zigbee2mqtt to 0
- Goto your cc2652p2 ESPHome webpage (e.g. http://192.168.1.90)
- Toggle `Prep the cc2652p2 for firmware update`
- Flash the device over the network

```bash
/usr/bin/python3 ./cc2538-bsl/cc2538-bsl.py -p socket://192.168.1.90:6638 -evw CC1352P2_CC2652P_launchpad_coordinator_20210120.hex
```

- Reboot the cc2652p2 via `Restart the Gateway` on the webpage
- Scale zigbee2mqtt back to 1
- 🎉 

✅  CC1352P2_CC2652P_launchpad_coordinator_20220219

## Routers

- Plug in router to your workstation
- Download and extract the newer firmware

```bash
curl -L \
  -o CC2652R_router_20220125.zip \
  https://github.com/Koenkk/Z-Stack-firmware/raw/master/router/Z-Stack_3.x.0/bin/CC2652R_router_20220125.zip

unzip CC2652R_router_20220125.zip
```

- Flash the device over USB

```bash
/usr/bin/python3 ./cc2538-bsl-master/cc2538-bsl.py -p /dev/tty.usbserial-1410 -evw ./CC2652R_router_20220125.hex
```

- 🎉 

✅  CC2652R_router_20210128

**Comment by onedr0p** [comment]
✅  Upgraded to CC1352P2_CC2652P_launchpad_coordinator_20210120.zip

**Comment by samip5** [comment]
I don't know how you managed to get the script to work as for me it's not able to open the socket. :(
