### ISSUE TITLE
Upgrade Intel NUC to latest BIOS firmware

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#1720]
# Details

https://www.intel.com/content/www/us/en/download/743906/bios-update-becfl357.html

**Comment by onedr0p** [comment]
✅  Upgraded to 0088

**Comment by onedr0p** [comment]
I don't think the BIOS version is accessible from the OS?

**Comment by sob** [comment]
I added an adhoc command to the taskfile to cat /sys/devices/virtual/dmi/id/bios_version. Seemed easier.

**Comment by onedr0p** [comment]
New firmware 0092 available.

**Comment by onedr0p** [comment]
Tracking in https://github.com/onedr0p/home-ops/issues/4939

**Comment by onedr0p** [comment]
New firmware 0095 available.

https://downloadmirror.intel.com/792123/BE_0095_ReleaseNotes.pdf

**Comment by onedr0p** [comment]
New firmware 0097 available

https://www.asus.com/us/supportonly/nuc8i7beh/helpdesk_bios/
