### ISSUE TITLE
Flux2 not reporting correct namespace in the prometheus metrics

### ISSUE THREAD

**Issue by ammmze** [onedr0p/home-ops#2229]
# Details

**What steps did you take and what happened:**

I recently copied the `PrometheusRule` you have for flux [here](https://github.com/onedr0p/home-cluster/blob/d5b56131b11c41360d28f2a345a033f3c0d3098a/cluster/apps/flux-system/monitoring/prometheus-rule.yaml#L20-L32). I got an alert for `HelmRelease` that was failing in my `home-iot` namespace, but the alert said it was in `flux-system`.

**What did you expect to happen:**

When an alert starts firing, I'd expect the namespace to be the same as the namespace the `HelmRelease` is placed in (i.e. `home-iot`.

**Anything else you would like to add:**

 I looked at the metrics in prometheus and it looks like the actual namespace we want is labeled as `exported_namespace`.

**Additional Information:**

Not sure if this was a recent change, or if it's something in my setup, or if it's always been this way. I just added this alert after upgrading to flux 0.18.

**Comment by onedr0p** [comment]
Were you able to figure this out @ammmze ?

**Comment by ammmze** [comment]
> Were you able to figure this out @ammmze ?

No, I haven't really looked yet. Got sucked into other things. So far still just using my modified rule looking at the `exported_nameapace`.

**Comment by onedr0p** [comment]
Going to close this issue, it appears it's a wontfix from the Flux guys. I was able to make it work in grafana as well.
