### ISSUE TITLE
Swap Flux GitRepository to use SSH on this repository

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#3168]
# Details

**Describe the solution you'd like:**

Give Flux back write access back to my cluster

**Comment by onedr0p** [comment]
Done. Steps to migrate from http are here https://github.com/k8s-at-home/template-cluster-k3s/issues/324

**Comment by Diaoul** [comment]
> Give Flux back write access back to my cluster

Curious why :detective:

**Comment by onedr0p** [comment]
No particular reason for me but this let's you have a private repo and also use the image automation controller.
