### ISSUE TITLE
Switch to using the Intel operator

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#4085]
# Details

**Describe the solution you'd like:**

Intel now supports deploying the Intel GPU plugin via their operator.

https://github.com/intel/helm-charts

**Comment by bjw-s** [comment]
It requires running an operator to deploy the plugin though :(

**Comment by onedr0p** [comment]
Also there isn't much benefit over just keeping it the way we currently deploy it, maybe in the future there will be more benefits. We'll see.

**Comment by onedr0p** [comment]
Maybe I'll cycle back to this one day.
