### ISSUE TITLE
Deploy actions runner controller

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#4391]
# Details

**Ask your question:**

**Comment by denniseffing** [comment]
@onedr0p quick question: How do you make sure that self-hosted runners do not pose a security risk for this public repository? As far as I understand, everyone who creates a PR using a fork of this repository is potentially able to run code as cluster admin using your runners.

**Comment by onedr0p** [comment]
All PRs from outside collaborators (e.g. not me) need to have approval for the workflows to run.

**Comment by denniseffing** [comment]
Could you link the code responsible for the approval process? I want to replicate the setup for my cluster as well and haven't found it yet.

Thank you!
