### ISSUE TITLE
Validate all images in helmrelease are ready

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#4539]
So many times getting burned merging in PRs where the image is not published or is not ready from the upstream helm chart sauce. Maybe I need to write a workflow to validate images can actually be pulled.

**Comment by Truxnell** [comment]
Stumbled across this one looking for something entirely unrelated.
I've been frustrated with this too, and took the approach of using renovates `stabilityDays` to delay PR's be a day to compensate - might be a simpler if lazier approach?

**Comment by onedr0p** [comment]
That would help in certain places for sure, I just wish there was a better way to verify images exist since `stabilityDays` isn't a sure fire way to verify. I would probably still need to verify on my local machine with `docker pull` on certain unnamed containers (cough cough emqx/bitnami)

**Comment by onedr0p** [comment]
I haven't had to worry about this in awhile, closing...
