### ISSUE TITLE
renovate regex are read twice

### ISSUE THREAD

**Issue by zaggash** [onedr0p/home-ops#4683]
Hi, I figured you have the same issue I had regarding regex being read twice.
https://github.com/onedr0p/home-ops/issues/2707

I worked on it here
https://github.com/renovatebot/renovate/discussions/19883#discussioncomment-4731502

Feel free to have a look if you're interested

TLDR: Split bot config and repo rules then call bot config from github action wokflow

**Comment by onedr0p** [comment]
I am not sure I am following here, but maybe it's too late in the afternoon 😄

**Comment by zaggash** [comment]
See here your regex

```
regex
    ansible/kubernetes/inventory/group_vars/all/k3s.yml
    ansible/router/inventory/group_vars/all/frr_exporter.yml
    ansible/router/inventory/group_vars/all/k8s_gateway.yml
    ansible/storage/inventory/group_vars/master/k3s.yml
    kubernetes/apps/monitoring/kube-prometheus-stack/app/patches/prometheus.yaml
    kubernetes/apps/system-upgrade/system-upgrade-controller/plans/agent.yaml
    kubernetes/apps/system-upgrade/system-upgrade-controller/plans/server.yaml
    ansible/kubernetes/inventory/group_vars/all/k3s.yml
    ansible/router/inventory/group_vars/all/frr_exporter.yml
    ansible/router/inventory/group_vars/all/k8s_gateway.yml
    ansible/storage/inventory/group_vars/master/k3s.yml
    kubernetes/apps/monitoring/kube-prometheus-stack/app/patches/prometheus.yaml
    kubernetes/apps/system-upgrade/system-upgrade-controller/plans/agent.yaml
    kubernetes/apps/system-upgrade/system-upgrade-controller/plans/server.yaml
```
You can see they are all listed twice.

This is because your config is read twice.
Once when the workflow is loaded then when the rules are loaded.

Basically Renovate will load the config file specified on the github action workflow.
In you case `RENOVATE_CONFIG_FILE: .github/renovate.json5`
It will use this file and merge the CLI and ENV config.
See the combined config : https://github.com/onedr0p/home-ops/actions/runs/3963568595/jobs/6791544770#step:5:139

A little later, it is actually loading default config files location defined here:
https://github.com/renovatebot/renovate/blob/ff648e687df564449241fb39716c5a514905b55f/lib/config/app-strings.ts#L1-L12  

Because your first config file have the same name as the exepected rules config files, it merge them and you can find it here:
https://github.com/onedr0p/home-ops/actions/runs/3963568595/jobs/6791544770#step:5:323


You can see that as an expected minimal bot config loaded at first from the workflow.
Then it is loading the rules from one of the files at the default locations

See how I fixed it here
https://github.com/zaggash/archlinux-aur

**Comment by onedr0p** [comment]
Thanks for the tl;dr I made the changes and looks to have fixed the dupes. That is weird indeed.
