### ISSUE TITLE
Support for hw transcoding using gid 106 (render)

### ISSUE THREAD

**Issue by naeramarth7** [onedr0p/home-ops#4937]
Took me some days to finally figure this out. Might help someone:
In addition - or apart from – the given groups, I had to add gid **106 (render)** to enable hw decoding on Debian 11 for Plex.

```
render:x:106:
```

https://github.com/onedr0p/home-ops/blob/6b0c4db69ebcb73d53d2eac1f52d8cdb2af31414/kubernetes/apps/default/plex/app/helmrelease.yaml#L66

![image](https://user-images.githubusercontent.com/2569015/222569196-7d29013c-a7ec-45ba-b446-6cf1134ec7d5.png)

![image](https://user-images.githubusercontent.com/2569015/222569226-75107ca2-dd40-444f-ba7d-5d2782bcca48.png)

via https://github.com/MichaIng/DietPi/issues/2916#issuecomment-503679311

**Comment by onedr0p** [comment]
109 is render on Ubuntu but good to know on Debian it is 106
