### ISSUE TITLE
Consider migrating prowlarr, radarr, lidarr and bazarr to postgresql

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#4942]
These applications support postgres and it might be a good idea to migrate from sqlite to postgres.

- Bazarr (cannot set postgres settings via env, only config file)
- Radarr
- Lidarr
- Prowlarr (consider running with `/config` as `emptyDir`)

May depend on: https://github.com/onedr0p/home-ops/issues/4448

**Comment by reefland** [comment]
Just got `cloudnative-pg` Postgres operator deployed.  I'm interested.

**Comment by mariusrugan** [comment]
@reefland peaking my nose in this open door, 

have already up and running is very easy. 
Consider first setting up backup (minio), testing it, testing the restore, and manoeuvring in the minor or major PG version upgrades. I also use pg for different other apps in the cluster.

**Comment by gwelican** [comment]
I've used this to move the data over: https://github.com/jeremyevans/sequel

the pgloader that the servarr article recommended, radarr just blew up on start. 

sequel is not perfect either, there were couple of boolean columns that became bigint, but it was an easy change (8-10 columns)

**Comment by onedr0p** [comment]
I was able to do this with pgloader, here's a rough guide...


```
# 1. Read
# https://wiki.servarr.com/lidarr/postgres-setup
# https://wiki.servarr.com/prowlarr/postgres-setup
# https://wiki.servarr.com/radarr/postgres-setup

# 2. Create the Database
docker run --network=host \
  -e INIT_POSTGRES_HOST="<postgres-host-or-ip>" \
  -e INIT_POSTGRES_SUPER_PASS="<postgres-su-password>" \
  -e INIT_POSTGRES_USER="radarr" \
  -e INIT_POSTGRES_PASS="<app-db-password>" \
  -e INIT_POSTGRES_DBNAME="radarr_main radarr_log" \
  ghcr.io/onedr0p/postgres-init:14.8

# 3. Seed the database
# Make sure you use the version of the app you currently have installed
docker run --network=host \
  -e LIDARR__POSTGRES_HOST="<postgres-host-or-ip>" \
  -e LIDARR__POSTGRES_PORT="5432" \
  -e LIDARR__POSTGRES_USER="radarr" \
  -e LIDARR__POSTGRES_PASSWORD="<app-db-password>" \
  -e LIDARR__POSTGRES_MAIN_DB="radarr_main" \
  -e LIDARR__POSTGRES_LOG_DB="radarr_log" \
  ghcr.io/onedr0p/radarr-develop:1.2.0.3183

# 3a. Kill container after migrations have ran

# 4. Drop tables if needed as described in the docs above

# 5. Clone https://github.com/Roxedus/Pgloader-bin and build it with docker
# 5a. `docker build --progress=plain -t pgloader:latest .`

# 6. Go to the radarr UI and create a backup, download it and extract it.

# 7. Run the migration
docker run --network=host \
  -v $(pwd)/radarr.db:/radarr.db \
  pgloader:latest \
  --with "quote identifiers" \
  --with "data only" \
  --with "prefetch rows = 100" \
  --with "batch size = 1MB" \
  /radarr.db \
  "postgresql://radarr:<app-db-password>@<postgres-host-or-ip>/radarr_main"

# 8. Ignore any PL/pgSQL function errors
# 9. Update your secrets in cluster for the app (check step 3 for required vars)
# 10. Success?
```

**Comment by reefland** [comment]
Have a feeling yet if it was worth the effort?

**Comment by onedr0p** [comment]
Apps seem to load a bit quicker, prowlarr doesn't need a config volume. bazarr, radarr and lidarr still do though for things. Overall I'll probably keep it this way.
