### ISSUE TITLE
incorrect url for frigate config schema

### ISSUE THREAD

**Issue by cbc02009** [onedr0p/home-ops#5186]
Just noticed this while I was trying to fix the same issue on my cluster.

per https://docs.frigate.video/configuration/#vscode-configuration-schema it should be `yaml-language-server: $schema=https://frigate.devbu.io/api/config/schema.json`

**Comment by onedr0p** [comment]
Gracias!

https://github.com/onedr0p/home-ops/commit/7500d0520a69836c2e9b51da04f6639dc552c46a
