### ISSUE TITLE
Volsync restore failing with "operation not permitted"

### ISSUE THREAD

**Issue by ammmze** [onedr0p/home-ops#5197]
I'm not sure if you've attempted to do a restore (or maybe this is something with my cluster) since you added the `moverSecurityContext` to the volsync `ReplicationSource` CRs, but I was just getting this set up in my cluster to finally move off of k10 and was testing a restore process and this was failing because we also need to set the `moverSecurityContext` in the `ReplicationDestination`. Without it, the pod trying to populate the destination gets a bunch of "operation not permitted" errors. I haven't looked to see if all of your `ReplicationSource`'s have the same security context...if they do you can just set it in your destination template. Otherwise, we probably need to see if we can update the task scripts to copy it from the `ReplicationSource` when creating the `ReplicationDestination`. Nice job on those tasks BTW...they make this a pretty slick process for backup/restore.

**Comment by onedr0p** [comment]
You can also try to add the namespace label like I've done here.

https://github.com/onedr0p/home-ops/blob/main/kubernetes/apps/default/namespace.yaml

**Comment by ammmze** [comment]
Ah...I didn't see that. Lemme try it.

**Comment by ammmze** [comment]
Cool...that does indeed work. Thank you!
