### ISSUE TITLE
How does SOPS work in your config?

### ISSUE THREAD

**Issue by hawkkiller** [onedr0p/home-ops#5339]
As I understood today, the encryption set in the flux kustomization toolkit only works in this layer (not below)

for example, having such structure

-- apps ( set encryption here )
---- weave-gitops
------ ks.yaml (that describes the deploy of weave-gitops app)

the encryption will not work until you set it in ks.yaml

Am I right? Because I just tried this approach in my cluster, and the SOPS decryption only worked when I set it in ks.yaml.

**Comment by onedr0p** [comment]
https://github.com/onedr0p/home-ops/blob/main/kubernetes/flux/apps.yaml#L25-L45

There's a patch that adds the decryption and provider to all ks files in the app directory.

**Comment by hawkkiller** [comment]
Thanks, now everything works! Shouldn't we add a note about this patch to the README?

**Comment by onedr0p** [comment]
While it's not super easy to spot it can be discovered. One can simply search my repo for the keywords of decryption or provider and find it. Plus there's this issue now which people can also discover if they search those terms 🙂
