### ISSUE TITLE
Ongoing updates to kube-vip after initial cluster bootstrap

### ISSUE THREAD

**Issue by lucidph3nx** [onedr0p/home-ops#6196]
Hi, I have been trying to figure out how kube-vip ends up being updated using your cluster setup.

I can see that [it is deployed initially](https://github.com/onedr0p/home-ops/blob/941288ddf290245daa5f65f4d4021b13c16aba6d/ansible/kubernetes/inventory/group_vars/all/main.yaml#L28-L29) using the k3s server pod manifests which deploys [this static pod](https://github.com/onedr0p/home-ops/blob/941288ddf290245daa5f65f4d4021b13c16aba6d/ansible/kubernetes/playbooks/templates/kube-vip-static-pod.yaml.j2), which has a tagged image version when it is initially copied over. But from there it seems like it is never imported into flux and cannot be updated using something like renovate to create PRs.

I see over at [flux-cluster-template](https://github.com/onedr0p/flux-cluster-template) you [appear to have a (possibly unreferenced?) file for updating kube-vip using anisble](https://github.com/onedr0p/flux-cluster-template/blob/419116d0140354848f5c848206b35ab4f92c39bd/bootstrap/templates/ansible/playbooks/cluster-kube-vip.yaml.j2) but I'm not sure if this is how it is intended to be used.
Ideally, Flux should take over management of kube-vip, so it can stay up to date with everything else in the cluster.

Are you able to clarify my understanding here? perhaps I have missed something.

Love your work by the way, I've learned so much about kubernetes from your projects.

**Comment by onedr0p** [comment]
Flux cannot manage static pods. The way I update isn't ideal, I just ssh into the master nodes and update the static pod manifest for kube-vip. The Ansible playbook in the template repo should also work but the amount of times I need to upgrade kube vip isn't enough for me to really dig in and automate it any other way.

**Comment by lucidph3nx** [comment]
That makes sense, consistent with my findings, and you're right, it is a rare occurrence to need to update kube-vip.
I'm curious though, can I ask why it isn't being installed the same way as cilium and coredns? Using server manifests which are then imported into flux later? Is it because they are not installed using a helm chart? or possibly that they there is a bootstrap race condition that expects the control plane vip to already exist before that?

I don't have a great understanding of how the bootstrap process works since I tend to build a cluster and let it run for a very long time. I should probably do it more regularly.

**Comment by onedr0p** [comment]
> or possibly that there is a bootstrap race condition that expects the control plane vip to already exist before that?

This exactly. If kube-vip wasn't a static pod the following would happen... coredns would be forever in a pending state due to cilium not working due to kube vip not working due to coredns not working.

**Comment by lucidph3nx** [comment]
Thanks for clarifying. I apologise, I completely missed that PR thread, it makes it quite clear why you've gone that particular route.

I do hope in future we can figure out a flux-only solution for ongoing management, but its not a big deal for now, its worth it for the benefits Cilium provides.

Thanks again, issue closed
