### ISSUE TITLE
Consider breaking up kube-system apps into separate namespaces

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/home-ops#6515]
I think cilium, coredns and metrics-server are the only apps I need in this namespace. It might be good to break some out into their own namespace(s)

**Comment by kashalls** [comment]
`cilium` seems like it should really be in the networking namespace... Same with `coredns`. `metrics-server` would be monitoring if you had to ask me.

**Comment by onedr0p** [comment]
I think having those 3 in `kube-system` as well with kube-vip is fine since they are very core components to the cluster

**Comment by onedr0p** [comment]
Done
