### ISSUE TITLE
Question on Ceph Version within Rook

### ISSUE THREAD

**Issue by reefland** [onedr0p/home-ops#6709]
If you have time for a question...  looking at your Rook-Ceph cluster deployment, I don't see how you control the version of Ceph installed as Rook supports 17.x and 18.x.

I've noticed my Ceph version stays at `17.2.6` while Rook has progressed from `v1.10.x`, `v11.x` and now `v12.x`.   I see Ceph version `17.2.7`  and `18.2.1` are available on Quay(https://quay.io/repository/ceph/ceph?tab=tags) but Renovate doesn't see them.

The Rook Cluster manifest supports 2 image locations, within: `toolbox:` and `cephClusterSpec.cephVersion`.  

Being that Ceph uses version numbers like `v17.2.7-20240103` it seems to require some Renovate trickery to understand the version and date combination. I got renovate to do a PR for `v17.2.6-20231027` -> `v17.2.7-20231027` but it should have found `v17.2.7-20240103`.

**Comment by onedr0p** [comment]
I am using the default Ceph version packaged with Rook, but you are free to upgrade to v18. I did last month but noticed some problems so I needed to rebuild my cluster back to v17. https://github.com/onedr0p/home-ops/commit/9b6d00bb938923915ef446c9a22486726b1742a8

For the renovate issue, I wouldn't pin to the date version, just use `v18.2.1` and renovate should pick it up.

**Comment by reefland** [comment]
The "default Ceph version" is not clear.  My default upon original install is `17.2.6` but when I review the projects [default helm values](https://github.com/rook/rook/blob/ba1959619076c9893d9c936712bd3a8b0b7bbe68/deploy/charts/rook-ceph-cluster/values.yaml#L98C37-L98C37) it is currently `18.2.1`.  

I plan on keeping 17.x for a few more months, its EOL in June 2024.  I'll set the non-date version for now, thanks for the response.

**Comment by onedr0p** [comment]
You are looking at an unreleased version of the helm chart. Looks like they are getting ready to release it.
