### ISSUE TITLE
rook-disk-job: bad dd flag

### ISSUE THREAD

**Issue by hur** [onedr0p/home-ops#7990]
### Describe the bug or feature request

Hi, I've been playing with cluster bootstrapping both with cluster-template and this repo on my own homelab. Came across what seems to be a bug in
`.taskfiles/Bootstrap/resources/rook-disk-job.tmpl.yaml`

The following:
```bash
dd if=/dev/zero of=${disk} bs=1M count=100 oflag=direct,dsync;
```
results in `dd: invalid argument 'dsync' to 'oflag'`. It seems like the alpine/coreutils `dd` does not support this flag (I'm running on amd64 for reference)?

I worked around this by removing the `dsync` flag.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Thanks for the info, looks like I added it here https://github.com/onedr0p/home-ops/commit/aa384f65450a774c57fb0ada3135fc641c05946b and probably didn't test it as the cluster was already running.
